# Generated by Django 4.1.7 on 2023-03-20 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roamapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='followers',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_follower', to='roamapi.traveler')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_with_subscribers', to='roamapi.traveler')),
            ],
        ),
        migrations.AddField(
            model_name='traveler',
            name='subscribers',
            field=models.ManyToManyField(related_name='subscriber', through='roamapi.Subscription', to='roamapi.traveler'),
        ),
    ]
