# Generated by Django 4.1.7 on 2023-03-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roamapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image_url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
